FROM python:3.11-slim

ARG project_dir=/app/
COPY ./app $project_dir
WORKDIR $project_dir

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["uvicorn", "app:app", "--host", "0.0.0.0"]